version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Mapear el puerto 8080 del host al puerto 80 del contenedor
    volumes:
      - ./backend:/var/www/html # Montar el directorio del backend en el contenedor
    environment:
      - APP_ENV=development # Configuración del entorno de Laravel (production, staging, development, etc.)

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapear el puerto 3000 del host al puerto 3000 del contenedor
    volumes:
      - ./frontend:/usr/src/app # Montar el directorio del frontend en el contenedor
    environment:
      - NODE_ENV=development # Configuración del entorno de Node.js (production, development, etc.)
      # Agrega otras variables de entorno necesarias para tu aplicación React Native